# Cvičení 2

Začnemě opakováním základů programovacího jazyka Python, tzn. tvorbou a prací s proměnnými, cykly (`for`) a podmínkami (`if, else, elif`). Následně se zaměříme na knihovnu Numpy, která slouží k práci vektory a maticemi.

## Práce s buňkami v notebooku

Připomeňme, že buňku (cell) s kódem v Jupyter Notebooku můžeme spustit těmito příkazy:
- `Ctrl + Enter` - spustí daný řádek kódu
- `Shift + Enter` - spustí daný řádek kódu a přejde na další řádek
- `Alt + Enter` - spustí daný řádek kódu a vytvoří nový řádek pod ním

Další možnost je využít tlačítko `Execute cell` vlevo nahoře od buňky.

## Základní aritmetické operace

Notebook (resp. Python interpret samotný) můžeme využít jako kalkulátor k základním výpočtům. Výsledky nemusíme ukládat do proměnných. Zkuste spustit následující buňky.

In [2]:
1+1

2

In [3]:
10*(2+3)

50

In [4]:
3*sin(3)

NameError: name 'sin' is not defined

Předchozí buňku nebylo možné spustit. Abychom mohli využívat pokročilejší matematické operace, musíme importovat příslušnou knihovnu (v tomto případě math nebo numpy). Projděte si a spusťte následující buňky.

In [5]:
import math
3*math.sin(3)           # Musíme volat s návzem knihovny "math."

0.4233600241796016

In [6]:
from math import sin
3*sin(math.pi)          # sin můžeme volat i bez návzu knihovny, před konstantu pi musíme stále  napsat "math."

3.6739403974420594e-16

**Pozor**: Následující přístup sice funguje a načte vše z knihovny `math`, ale je považován za **špatný zvyk**. Nevíte, co vše se z knihovny načetlo, názvy importovaných proměnných a funkcí mohou **kolidovat** s vašimi názvy nebo s funkcemi načtenými z jiných knihoven.

**Nevyužívejte**, pokud to není nezbytně nutné. 

In [7]:
from math import *
3*acos(sin(pi))         # Načte se vše z knihovny math, vše lze volat bez počátečního "math."

4.71238898038469

## Proměnné 

Proměnné definujeme pomocí znaku `=`. Typ proměnné není nutné specifikovat (Python je dynamicky typovaný jazyk, typ proměnné určí interpret jazyka automaticky).

In [8]:
a = 5
b = math.pi
c = "Hello world"

print(a)
print(b)
print(c)

5
3.141592653589793
Hello world


Jakého typu je daná proměnná můžeme zjistit pomocí příkazu `type`.

In [9]:
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>


## `for` cyklus

Pro cyklus s předem daným počtem iterací využíváme příkaz `for`. Základní použití je v kombinaci s příkazem `range`, pomocí kterého vytvoříme tzv. iterovatelný objekt:

- `range(n)` - vytvoří iterovatelný objekt, který obsahuje čísla od 0 do n-1
- `range(m, n)` - vytvoří iterovatelný objekt, který obsahuje čísla od m do n-1
- `range(m, n, k)` - vytvoří iterovatelný objekt, který obsahuje čísla od m do n-1 s krokem k

Následující kód iteruje od 0 do 5 a vypíše současnou hodnotu `i`.

In [10]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [11]:
# UKOL: Doplňte kód, který vypíše sudá čísla od 2 do 10 (včetně):

for k in range(2, 11, 2):
    print(k)

2
4
6
8
10


## Podmínky

K vytváření podmíněných bloků kódu slouží příkazy `if`, `else`, `elif`.

K porovnávání mezi hodnotami používáme operátory `==`, `>=`, `<=`, `>`, `<`, `!=`

In [12]:
x = 0.5

if (abs(x) <= 1):
    y = math.acos(x)
    print("acos(x) = {}".format(y))
else:
    print("Hodnota proměnné je mimo definiční obor funkce.")

acos(x) = 1.0471975511965979


In [13]:
""" 
UKOL: Doplňte následující kód tak, aby 
1) smyčka iterovala od 1 do 20 včetně
2) vypsal aktuální i
3) pokud je aktuální i sudé, vypsal na dalším řádku "Sudé číslo"
4) pokud je aktuální i liché, vypsal na dalším řádku "Liché číslo"

K určení toho, zda je číslo sudé, potřebujete modulo operátor % - zbytek po 
celočíselném deleni. (zbytek = delenec % delitel) 

"""

for i in range(1, 21):
    print(i)
    if(i%2==0):
        print("Sudé číslo")
    else:
        print("Liché číslo")

1
Liché číslo
2
Sudé číslo
3
Liché číslo
4
Sudé číslo
5
Liché číslo
6
Sudé číslo
7
Liché číslo
8
Sudé číslo
9
Liché číslo
10
Sudé číslo
11
Liché číslo
12
Sudé číslo
13
Liché číslo
14
Sudé číslo
15
Liché číslo
16
Sudé číslo
17
Liché číslo
18
Sudé číslo
19
Liché číslo
20
Sudé číslo


## Knihovna NumPy

V tomto kurzu budeme pracovat hlavně s knihovnou `NumPy`, základní knihovnou pro vědecké výpočty v Pythonu. Umožňuje nám manipulaci s vektory a maticemi, implementuje operace mezi nimi či maticové rozklady.

In [15]:
import numpy as np      #  np je běžně využívaná zkratka pro numpy

Matice a vektory můžeme vytvořit např. pomocí:

- `np.array()` - vytvoří vektor/matici z listu
- `np.zeros()` - vytvoří vektor/matici o daných rozměrech, která je naplněna nulami
- `np.ones()` - vytvoří vektor/matici o daných rozměrech, která je naplněna jedničkami
- `np.linspace()` - vytvoří vektor o daných rozměrech, který obsahuje čísla od m do n-1 s krokem k
- `np.eye()` - vytvoří jednotkovou matici o daných rozměrech
- `np.random.rand()` - vytvoří vektor/matici o daných rozměrech, která je naplněna náhodnými čísly z intervalu [0, 1)

(Vzpomeňte si, že dokumentaci k jednotlivým funkcím s detailnějším popisem můžete zavolat pomocí příkazu `help`, např. `help(np.linspace)`)

Příklady použití:

In [16]:
b = np.array([1, 2, 3, 4])
print(b)

[1 2 3 4]


In [17]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A) 

[[1 2 3]
 [4 5 6]]


In [18]:
e = np.ones(4)
print(e)

[1. 1. 1. 1.]


In [19]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
"""
ÚKOL: 
1) Vytvořte matici A samých nul, která má 4 řádky a 3 sloupce.
2) Vytvořte náhodný vektor b o čtyřech prvcích.
3) Vytvořte vektor v obsahující 10 čísel rovnoměrně rozmístěných mezi 0 a 5 včetně.
"""
A = np.zeros((4,3))
print(A)

print("\n")
b = np.random.rand(4)
print(b)

print("\n")
c = np.linspace(0, 5, 10)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[0.84713122 0.1507154  0.53191659 0.94961254]


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Chceme-li přistupovat k prvkům matice či vektoru v NumPy, využíváme hranaté závorky `[]` a indexujeme od nuly. 

In [22]:
b = np.array([0, 1, 2, 3, 4])
print(b)

x = b[1]        # druhý prvek vektoru b
print(x)

x = b[0:3]      # prvky na pozicích 0 až 2
print(x)

x = b[0:5:2]    # každý druhý prvek vektoru, (zopakujme syntaxi: x = b[start:end+1:krok])
print(x)

x = b[[1, 3]]   # prvky na pozicích 1, 3
print(x)

x = b[-1]       # můžeme indexovat odzadu, indexem -1 získáme poslední prvek, -2 předposlední, atd.
print(x)

[0 1 2 3 4]
1
[0 1 2]
[0 2 4]
[1 3]
4


In [23]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(A)

a = A[0, 0]         # prvek na pozici (0, 0)
print(a)

a = A[1, 3]         # prvek na pozici (1, 3)
print(a)

B = A[0, 1:3]       # prvky na prvním řádku v druhém až třetím sloupci (v řeči indexů - na 0. řádku a 1. až 3. sloupci bez 3. sloupce)
print(B)

[[1 2 3 4]
 [5 6 7 8]]
1
8
[2 3]


In [24]:
"""
ÚKOL: 
1) Vytvořte náhodnou matici o rozměrech 5x5.
2) Do vektoru v uložte poslední řádek matice, vektor vytiskněte.
3) Do vektoru u uložte prvky na druhém řádku matice v prvním a posledním sloupci, vytiskněte.
"""
M = np.random.rand(5, 5)
print(M)

print("\n")
v = M[-1]
print(v)

print("\n")
u = M[1, [0, -1]]
print(u)

[[0.50819307 0.71625461 0.24297635 0.2720305  0.15168996]
 [0.18177059 0.58301117 0.4960698  0.63461508 0.00503636]
 [0.46718853 0.70990547 0.009944   0.66396683 0.53554493]
 [0.06604929 0.71532356 0.27199577 0.11557631 0.07264562]
 [0.21288589 0.56051524 0.48554955 0.92278156 0.18025552]]


[0.21288589 0.56051524 0.48554955 0.92278156 0.18025552]


[0.18177059 0.00503636]


Vektory v NumPy mohou být reprezentovány jako 
1) 1D pole, např. `x = np.array([1, 2, 3])` nebo `y = ones(6)`
2) 2D pole ve formě řádku, např. `x = np.array([[1, 2, 3]])` nebo `y = np.zeros((1, 4))`
3) 2D pole ve formě sloupce, např. `x = np.array([[1], [2], [3]])`, `y = np.zeros((5, 1))` nebo `y = np.array([[1, 2, 3]]).T`

Vzhledem k tomu, že vektory budeme využívat zejména k účelům algoritmů lineární algebry, doporučuji vám je rovnou vytvářet ve 2D formě jako řádek nebo sloupec. Další možnost je vytvořit 1D pole a to _reshapovat_ na správné rozměry.

In [25]:
x = np.array([1, 2, 3])     # vytvoří 1D pole (ani řádek, ani sloupec)
x = x.reshape(3, 1)         # konvertuje x na 2D sloupcový vektor
print(x)
print(np.shape(x))          # vytiskne rozměry x 

print("---------------------")

y = np.array([1, 2, 3]).T   # vytvoříme řádkový vektor a transponujeme jej
print(y)
print(np.shape(y))

[[1]
 [2]
 [3]]
(3, 1)
---------------------
[1 2 3]
(3,)


In [43]:
"""
ÚKOL: 
1) Vytvořte náhodný sloupcový vektor x délky 5 a náhodný řádkový vektor y délky 5
2) Pomocí vhodných funkcí z knihovny NumPy určete 
    - normu vektoru x
    - skalární součin vektoru y s vektorem x
    - součet vektoru x s transpozicí vektoru y
"""

x = np.random.rand(5)
y = np.random.rand(5)

print(x)
print("\n")
print(y)

print("\nNorma vektoru:")
print(np.linalg.norm(x))
print("\nSkalar. souc.:")
print(np.dot(x,y))
print("\nSoucet:")
print(x + y.T)

[6.30470956e-02 8.26059761e-01 6.70858751e-04 4.43515517e-01
 2.48551241e-01]


[0.90204442 0.77143038 0.16370449 0.60425463 0.30224725]

Norma vektoru:
0.9720256415302414

Skalar. souc.:
1.0373489293266849

Soucet:
[0.96509152 1.59749014 0.16437534 1.04777015 0.55079849]


In [45]:
"""
ÚKOL:
Vypočítejte nyní normu vektoru x a skalární součin y*x "manuálně" pomocí cyklů for.
"""
sum = 0
for i in range(0, 5): 
    sum += pow(x[i], 2)
nX = sqrt(sum)
print(nX)

sum = 0
for i in range(0, 5):
    sum += x[i] * y[i]
print(sum)



0.9720256415302414
1.0373489293266849


NumPy podporuje také samozřejmě také násobení matice s vektorem či matice s maticí. K tomu lze využít funkci `matmul` nebo operátor `@`.

In [46]:
A = np.ones((3, 3))
x = np.array([0, 1, 2])
x = x.reshape(3, 1)         # převedeme x na sloupcový vektor abychom jím mohli násobit matici zprava

y = np.matmul(A, x)         # násobení pomocí matmul
print(y)

z = A @ x                   # násobení pomocí operátoru @
print(y)

B = np.random.rand(3, 3)
C = np.matmul(A, B)
print(C)

[[3.]
 [3.]
 [3.]]
[[3.]
 [3.]
 [3.]]
[[2.00977909 0.43643765 1.58923973]
 [2.00977909 0.43643765 1.58923973]
 [2.00977909 0.43643765 1.58923973]]


In [53]:
"""
ÚKOL:
Do funkce muj_matvec implementujte vaši verzi násobení matice s vektorem.
Využijte dvě vnořené smyčky for. Na vstupu bude matice A a sloupcový vektor x 
odpovídající délky. Funkce bude vracet vektor y = Ax.
"""

def muj_matvec(A, x):
    m, n = np.shape(A)      # tuple unpacking, m obsahuje počet řádků, n počet sloupců matice A
    y = np.zeros(m)    

    for i in range(m):
        for j in range(n):
            y[i] += A[i][j] * x[j][0]
            

    return y

In [54]:
# Zde si voláním funkce ověřte, zda funguje správně:

A = np.random.rand(3, 4)
x = np.random.rand(4, 1)
y = muj_matvec(A, x)
print(y)        # vytiskneme výsledek z vaší funkce

yy = A @ x
print(yy)       # porovnejte s voláním zabudované numpy funkce

[0.9966266  0.38837209 0.97169041]
[[0.9966266 ]
 [0.38837209]
 [0.97169041]]


In [55]:
# Porovnáme časy výpočtu pomocí vaší funkce a zabudované numpy funkce
import time

A = np.random.rand(2000, 2000)
x = np.random.rand(2000, 1)

# otestujeme vaši implementaci 
st = time.time()
y = muj_matvec(A, x)
et = time.time()

your_time = et - st

# otestujeme zabudovanou implementaci
st = time.time()
yy = A @ x
et = time.time()

numpy_time = et - st

print("Čas výpočtu pomocí vaší funkce: {} sekund".format(your_time))
print("Čas výpočtu pomocí numpy funkce: {} sekund".format(numpy_time))

Čas výpočtu pomocí vaší funkce: 1.893509864807129 sekund
Čas výpočtu pomocí numpy funkce: 0.0015468597412109375 sekund


Implementujte nyní násobení matice-vektor na základě předpisu $$A\mathbf{x} = \sum_{i=1}^n x_i \mathbf{a}_i,$$
kde $\mathbf{a}_i$ je $i$-tý sloupec matice $A$ a $x_i$ je příslušný prvek vektoru $\mathbf{x}$.

Nápověda: budete-li chtít vytáhnout sloupec matice pomocí příkazu `A[:, i]`, NumPy redukuje dimenzi a vrátí 1D vektor. Pro získání 2D sloupcového vektoru je třeba zavolat `A[:, [i]]`.

In [56]:
# ÚKOL: Doplňte implementaci.

def muj_matvec_v2(A, x):
    m, n = np.shape(A)      
    
    y = np.zeros((m, 1))

    for i in range(n):
        ai = A[:, [i]]
        y += x[i, 0] * ai

    return y

In [57]:
# Ověřte funkčnost :
A = np.random.rand(3, 4)
x = np.random.rand(4, 1)

y = muj_matvec_v2(A, x)
print("Výsledek z funkce:")
print(y)

print("Kontrola pomocí @:")
print(A @ x)


Výsledek z funkce:
[[1.35991713]
 [1.52324039]
 [1.21474164]]
Kontrola pomocí @:
[[1.35991713]
 [1.52324039]
 [1.21474164]]


In [58]:
# Otestujte na stejně velké matici jako vaši předchozí verzi a porovnejte výpočetní časy. 
# Liší se časy významně? Pokud ano, pokuste se zdůvodnit proč.

A = np.random.rand(2000, 2000)
x = np.random.rand(2000, 1)

# otestujeme vaši implementaci 
st = time.time()
y = muj_matvec_v2(A, x)
et = time.time()

your_time = et - st

# otestujeme zabudovanou implementaci
st = time.time()
yy = A @ x
et = time.time()

numpy_time = et - st

print("Čas výpočtu pomocí vaší funkce: {} sekund".format(your_time))
print("Čas výpočtu pomocí numpy funkce: {} sekund".format(numpy_time))

Čas výpočtu pomocí vaší funkce: 0.020079374313354492 sekund
Čas výpočtu pomocí numpy funkce: 0.0013613700866699219 sekund


In [59]:
# Bonus: Pokuste se implementovat funkci mat_mat, která bude násobit dvě matice. 
# Porovnejte výkon s funkcí z knihovny NumPy.

def mat_mat(A, B):
    m = len(A)
    n = len(A[0])
    p = len(B[0])
    C = [[0 for _ in range(p)] for _ in range(m)]

    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C


In [60]:
A = np.random.rand(200, 300)
B = np.random.rand(300, 150)

A_list = A.tolist()
B_list = B.tolist()

start = time.time()
C_manual = mat_mat(A_list, B_list)
end = time.time()
print("Doba běhu manuální funkce:", end - start, "s")

start = time.time()
C_numpy = A @ B
end = time.time()
print("Doba běhu NumPy:", end - start, "s")

Doba běhu manuální funkce: 0.6574864387512207 s
Doba běhu NumPy: 0.0004296302795410156 s
