# Cvičení 3

Tématem tohoto cvičení jsou přímé metody řešení soustav lineárních rovnic. Budeme se zabývat dopřednou a zpětnou substitucí a LU rozkladem.

## Dopředná a zpětná substituce

Základní princip přímých metod řešení soustav lineárních rovnic je převod matice soustavy na součin trojúhelníkových matic, např. 
$$\mathsf{A} = \mathsf{L}\mathsf{U}.$$
Soustavu $\mathsf{A}\mathbf{x} = \mathbf{b}$ tak převedeme na tvar
$$\mathsf{L}\mathsf{U}\mathbf{x} = \mathbf{b}$$
a vyřešíme ji ve dvou krocích 
1) $\mathsf{L}\mathbf{y}=\mathbf{b}$
2) $\mathsf{U}\mathbf{x}=\mathbf{y}$
pomocí dopředné a zpětné substituce.

V této části cvičení tedy nejdříve implementujeme funkce pro dopřednou a zpětnou substituci, které později využijeme k řešení soustav.

### Testovací matice

Nejprve vygenerujte testovací matice, pomocí kterých později zjistíte, zda vaše funkce pracují správně. Budete k tomu potřebovat
- funkci z knihovny NumPy, pomocí které vygenerujete náhodnou matici o daném rozměru (znáte z prvního cvičení),
- funkce `triu`, `tril` z knihovny NumPy (zjistěte v dokumentaci nebo pomocí Googlu, k čemu slouží a jak se používají)

In [1]:
# ÚKOL: importujte potřebnou knihovnu NumPy pod zkratkou np

import numpy as np

In [2]:
# ÚKOL: vygenerujte matici A náhodných čísel o rozměrech 4x4
A = np.random.rand(4, 4)

np.set_printoptions(precision=3) # pro lepší přehlednost
print(A)

[[0.631 0.62  0.898 0.48 ]
 [0.299 0.423 0.022 0.503]
 [0.363 0.948 0.494 0.488]
 [0.634 0.017 0.18  0.929]]


In [3]:
# ÚKOL: pomocí vhodných funkcí z knihovny NumPy extrahujte z matice A její horní a dolní trojúhelníkovou část.
U = np.triu(A)
print(U)
print("---------------------")

L = np.tril(A)
print(L)

# Ověřte funkčnost porovnáním s příslušnou částí matice A

[[0.631 0.62  0.898 0.48 ]
 [0.    0.423 0.022 0.503]
 [0.    0.    0.494 0.488]
 [0.    0.    0.    0.929]]
---------------------
[[0.631 0.    0.    0.   ]
 [0.299 0.423 0.    0.   ]
 [0.363 0.948 0.494 0.   ]
 [0.634 0.017 0.18  0.929]]


In [4]:
# ÚKOL: Vytvořte náhodný vektor b délky 4
b = np.random.rand(4)

print(b)

[0.767 0.242 0.092 0.06 ]


### Dopředná substituce

Soustavu s dolní trojúhelníkovou maticí $\mathsf{L}\mathbf{x}=\mathbf{b}$ můžeme efektivně řešit pomocí algoritmu dopředné substituce. 

1) Určíme první prvek vektoru řešení
$$x_1 = b_1 / L_{1, 1}$$

2) Zbývající prvky určíme jako 
$$\forall i \in \{2, 3, \ldots, m\}: x_i = (b_i - \sum_{j=1}^{i-1}L_{i, j} x_j) / L_{i, i}$$

Na základě těchto předpisů doplňte chybějící části následujícího kódu. Nezapomeňte ale, že v Pythonu indexujeme od nuly.

In [5]:
# ÚKOL: Doplňte následující kód

def fsubst(L, b):
    m, n = L.shape             # pomocí vhodné funkce numpy uložte do proměnných m, n počet řádků a sloupců L
    x = np.zeros(n)                # vytvořte vektor samých nul délky n

    x[0] = b[0] / L[0, 0]   # první prvek řešení

    for i in range(1, m):

        # nejdříve pomocí vnořeného for cyklu určíme hodnotu sumy z kroku 2:
        suma = 0
        for j in range(0, i):                           # doplňte vhodně meze smyčky
            suma += L[i, j] * x[j]                        # doplňte

        # odečteme sumu od prvku pravé strany a vydělíme diagonálním prvkem
        x[i] = (b[i] - suma) / L[i, i]                             # doplňte

    return x


In [6]:
# Otestujte pomocí L, b
x = fsubst(L, b)
print(x)

[ 1.215 -0.287 -0.155 -0.729]


In [7]:
# ÚKOL: určete řešení pomocí funkce solve z numpy a porovnejte s vašim řešením
x_numpy = np.linalg.solve(L, b)
print(x_numpy)

[ 1.215 -0.287 -0.155 -0.729]


### Zpětná substituce

K vyřešení soustavy s horní trojúhelníkovou maticí $\mathsf{U}\mathbf{x} = \mathbf{b}$ potřebujeme implementovat také algoritmus zpětné substituce. Ten je podobný dopředné substituci, postupuje však od posledního řádku:

1) Určíme poslední prvek vektoru řešení 
$$x_m = b_m / U_{m,m}$$
2) Určíme zbývající prvky
$$\forall i \in \{m-1, m-2, \ldots, 1\}: x_i = (b_i - \sum_{j=i+1}^{m}U_{i, j}x_j) / U_{i, i}$$

Implementujte v následující buňce vaši verzi zpětné substituce.

**Poznámka** Při implementaci se vám bude hodit vědět, že funkce range umožňuje iterovat i "pozpátku". Vyzkoušejte si v následující buňce vytisknout přes jaká *i* iterují tyto `for` cykly:
- `for i in range(6, 0, -1)`
- `for i in range(6, -1, -1)`
- `for i in range(6, 0, -2)`
- `for i in range(0, -6, -1)`

In [11]:
# ÚKOL: Vytiskněte proměnnou i z příkladů v předchozí buňce.

for i in range(6, 0, -1):
    print(i)

print("")
for i in range(6, -1, -1):
    print(i)

print("")
for i in range(6, 0, -2):
    print(i)

print("")
for i in range(0, -6, -1):
    print(i)

6
5
4
3
2
1

6
5
4
3
2
1
0

6
4
2

0
-1
-2
-3
-4
-5


In [13]:
# ÚKOL: Implementujte algoritmus zpětné substituce.

def b_subst(U, b):
    m, n = U.shape
    x = np.zeros(n)

    x[n-1] = b[n-1] / U[n-1, n-1]

    for i in range(n-2, -1, -1):
        suma = 0

        for j in range(i+1, n):
            suma += U[i, j] *x[j]

        x[i] = (b[i] - suma) / U[i, i]

    return x

In [14]:
# ÚKOL: ověřte pomocí numpy, že vaše funkce vrací správný výsledek

x2 = b_subst(U, b)
x2_numpy = np.linalg.solve(U, b) # doplňte
print(x2)
print(x2_numpy)

[0.514 0.488 0.121 0.065]
[0.514 0.488 0.121 0.065]
